version: '3'
services:
  base:
    image: osmesa_analytics:latest
    build:
      context: .
      dockerfile: analytics_base.dockerfile
  augdiff_stream:
    image: augdiff_stream:latest
    build:
      context: .
      dockerfile: augdiff_stream.dockerfile
  changeset_stream:
    image: changeset_stream:latest
    build:
      context: .
      dockerfile: changeset_stream.dockerfile
